FROM fedora:34

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN dnf install -y R-core gsl-devel libcurl-devel libxml2-dev fontconfig-devel openssl-devel udunits2-devel harfbuzz-devel fribidi-devel && \
    echo 'options("repos" = c(CRAN="https://cloud.r-project.org/"))' >> ~/.Rprofile && \
    Rscript -e "install.packages(c('devtools', 'Rcpp', 'RcppArmadillo', 'sf'), Ncpus = parallel::detectCores(), quiet = T)"

ENTRYPOINT [ "R" ]
